@ApiService_HostAddress = http://localhost:5348

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/politician/search?query=nan&Limit=5
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/politician/T000250
Accept: application/json

### 

GET {{ApiService_HostAddress}}/api/politician/T000250/trades
Accept: application/json

### 

GET {{ApiService_HostAddress}}/api/trades/recent
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/stock/search?query=APP&Limit=10
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/stock/AAPL
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/stock/AAPL/trades
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/traders/most-active
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/stocks/most-active
Accept: application/json

###

POST https://app-pub-pri-elastic.azurewebsites.net/search
Content-Type: application/json

{"index":"bioguideprofiles","matches":[{"fields":["usCongressBioId"],"query":"G000359"}]}

###

GET https://finnhub.io/api/v1/search?q=zzff&exchange=US&token={{finnhub.apiKey}}
Content-Type: application/json