@ApiService_HostAddress = http://localhost:5348

GET {{ApiService_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{ApiService_HostAddress}}/api/politicians/search?query=nan&Limit=5
Accept: application/json

### 

POST https://app-pub-pri-elastic.azurewebsites.net/search
Content-Type: application/json

{"index":"bioguideprofiles","matches":[{"fields":["usCongressBioId"],"query":"G000359"}]}
