// <auto-generated />
using System;
using CongressionalTradingTracker.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CongressionalTradingTracker.Infrastructure.Migrations
{
    [DbContext(typeof(TradeDbContext))]
    [Migration("20260321215515_AddNewCongressGovFields")]
    partial class AddNewCongressGovFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Politician", b =>
                {
                    b.Property<int>("PoliticianId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PoliticianId"));

                    b.Property<string>("BioGuideId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("District")
                        .HasColumnType("integer");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageAltText")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("PoliticianId");

                    b.HasIndex("BioGuideId")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Politicians_Name_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                    b.ToTable("Politicians");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.SyncState", b =>
                {
                    b.Property<int>("SyncStateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SyncStateId"));

                    b.Property<bool>("BulkSyncCompleted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastLiveSyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SyncStateId");

                    b.ToTable("SyncStates");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Ticker", b =>
                {
                    b.Property<int>("TickerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TickerId"));

                    b.Property<string>("Company")
                        .HasColumnType("text");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TickerType")
                        .HasColumnType("text");

                    b.HasKey("TickerId");

                    b.HasIndex("Company")
                        .HasDatabaseName("IX_Ticker_Company_trgm");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Company"), "gin");
                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Company"), new[] { "gin_trgm_ops" });

                    b.HasIndex("Symbol")
                        .IsUnique();

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Trade", b =>
                {
                    b.Property<int>("TradeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TradeId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("District")
                        .HasColumnType("text");

                    b.Property<decimal?>("ExcessReturn")
                        .HasColumnType("numeric");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Party")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PoliticianId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("PriceChange")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RangeMax")
                        .HasColumnType("numeric");

                    b.Property<decimal?>("RangeMid")
                        .HasColumnType("numeric");

                    b.Property<decimal>("RangeMin")
                        .HasColumnType("numeric");

                    b.Property<string>("RawAmount")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RawRange")
                        .HasColumnType("text");

                    b.Property<DateTime>("ReportDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("SpyChange")
                        .HasColumnType("numeric");

                    b.Property<string>("SubHolding")
                        .HasColumnType("text");

                    b.Property<int>("TickerId")
                        .HasColumnType("integer");

                    b.Property<string>("Transaction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TradeId");

                    b.HasIndex("TickerId");

                    b.HasIndex("TransactionDate")
                        .HasDatabaseName("IX_Trades_TransactionDate");

                    b.HasIndex("PoliticianId", "TickerId", "TransactionDate", "ReportDate", "Transaction", "RawAmount", "SubHolding")
                        .IsUnique();

                    b.ToTable("Trades");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Trade", b =>
                {
                    b.HasOne("CongressionalTradingTracker.Domain.Politician", "Politician")
                        .WithMany("Trades")
                        .HasForeignKey("PoliticianId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CongressionalTradingTracker.Domain.Ticker", "Ticker")
                        .WithMany("Trades")
                        .HasForeignKey("TickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Politician");

                    b.Navigation("Ticker");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Politician", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("CongressionalTradingTracker.Domain.Ticker", b =>
                {
                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
