/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as StockRouteImport } from './routes/stock'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PoliticianCompareRouteImport } from './routes/politician-compare'
import { Route as PoliticianRouteImport } from './routes/politician'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StockSymbolRouteImport } from './routes/stock_.$symbol'
import { Route as PoliticianBioguideidRouteImport } from './routes/politician_.$bioguideid'

const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const StockRoute = StockRouteImport.update({
  id: '/stock',
  path: '/stock',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticianCompareRoute = PoliticianCompareRouteImport.update({
  id: '/politician-compare',
  path: '/politician-compare',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticianRoute = PoliticianRouteImport.update({
  id: '/politician',
  path: '/politician',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StockSymbolRoute = StockSymbolRouteImport.update({
  id: '/stock_/$symbol',
  path: '/stock/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticianBioguideidRoute = PoliticianBioguideidRouteImport.update({
  id: '/politician_/$bioguideid',
  path: '/politician/$bioguideid',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/politician': typeof PoliticianRoute
  '/politician-compare': typeof PoliticianCompareRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/politician/$bioguideid': typeof PoliticianBioguideidRoute
  '/stock/$symbol': typeof StockSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/politician': typeof PoliticianRoute
  '/politician-compare': typeof PoliticianCompareRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/politician/$bioguideid': typeof PoliticianBioguideidRoute
  '/stock/$symbol': typeof StockSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/feedback': typeof FeedbackRoute
  '/politician': typeof PoliticianRoute
  '/politician-compare': typeof PoliticianCompareRoute
  '/settings': typeof SettingsRoute
  '/stock': typeof StockRoute
  '/watchlist': typeof WatchlistRoute
  '/politician_/$bioguideid': typeof PoliticianBioguideidRoute
  '/stock_/$symbol': typeof StockSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/feedback'
    | '/politician'
    | '/politician-compare'
    | '/settings'
    | '/stock'
    | '/watchlist'
    | '/politician/$bioguideid'
    | '/stock/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/feedback'
    | '/politician'
    | '/politician-compare'
    | '/settings'
    | '/stock'
    | '/watchlist'
    | '/politician/$bioguideid'
    | '/stock/$symbol'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/feedback'
    | '/politician'
    | '/politician-compare'
    | '/settings'
    | '/stock'
    | '/watchlist'
    | '/politician_/$bioguideid'
    | '/stock_/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FeedbackRoute: typeof FeedbackRoute
  PoliticianRoute: typeof PoliticianRoute
  PoliticianCompareRoute: typeof PoliticianCompareRoute
  SettingsRoute: typeof SettingsRoute
  StockRoute: typeof StockRoute
  WatchlistRoute: typeof WatchlistRoute
  PoliticianBioguideidRoute: typeof PoliticianBioguideidRoute
  StockSymbolRoute: typeof StockSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock': {
      id: '/stock'
      path: '/stock'
      fullPath: '/stock'
      preLoaderRoute: typeof StockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politician-compare': {
      id: '/politician-compare'
      path: '/politician-compare'
      fullPath: '/politician-compare'
      preLoaderRoute: typeof PoliticianCompareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politician': {
      id: '/politician'
      path: '/politician'
      fullPath: '/politician'
      preLoaderRoute: typeof PoliticianRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stock_/$symbol': {
      id: '/stock_/$symbol'
      path: '/stock/$symbol'
      fullPath: '/stock/$symbol'
      preLoaderRoute: typeof StockSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politician_/$bioguideid': {
      id: '/politician_/$bioguideid'
      path: '/politician/$bioguideid'
      fullPath: '/politician/$bioguideid'
      preLoaderRoute: typeof PoliticianBioguideidRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FeedbackRoute: FeedbackRoute,
  PoliticianRoute: PoliticianRoute,
  PoliticianCompareRoute: PoliticianCompareRoute,
  SettingsRoute: SettingsRoute,
  StockRoute: StockRoute,
  WatchlistRoute: WatchlistRoute,
  PoliticianBioguideidRoute: PoliticianBioguideidRoute,
  StockSymbolRoute: StockSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
